language: go
go:
- 1.5.1
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="fischcheng"
  - GIT_EMAIL="fischcheng@gmail.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="source"
before_install:
- openssl aes-256-cbc -K $encrypted_a854d1f06033_key -iv $encrypted_a854d1f06033_iv
  -in travis_key.enc -out travis_key -d

before_script:
- go get -u -v github.com/spf13/hugo
script:
- hugo
after_success:
- "./deploy.sh"
