baseurl = "https://fischcheng.github.io/"
title = "Yu Cheng"
copyright = "&copy; 2016 Yu Cheng"
#languageCode = "en-us"
theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"



# Enable comments by entering your Disqus shortname
disqusShortname = "yucheng"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-92668349-1"


# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false


[blackfriday]
hrefTargetBlank = true
fractions = false
# color-codes for highlighting derived from this style
#PygmentsCodeFences= true
#pygmentsStyle= "monokai"


[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
  name = "Yu Cheng 鄭嵎"
  role = "PhD candidate"
  organization = "RSMAS / University of Miami"
  organization_url = "http://www.rsmas.miami.edu"
  avatar = "headshot.jpg"
  email = "yucheng@rsmas.miami.edu"
  address = "4600 Rickenbacker Causeway, Miami, FL 33149, USA"
  #phone = "786 503 3366"
  office_hours = ""
  phone = ""
  #skype = "dennis_yu0123"
  telegram = ""


  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = true

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
  custom_css = ["green.css"]   # change the default color theme to green using a custom_css, can be altered later
  custom_js  = []


  #highlighting
  highlight = true
  highlight_languages = ["python","ncl","matlab","latex"]
  highlight_style = "github"
  highlight_version = "9.9.0"


  # Publication types.
  #   Used to categorize publications.
  #   The index of the publication type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a publication's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  publication_types = [
    'Uncategorized',  # 0
    'Conference proceedings',  # 1
    'Journal',  # 2
    'Work in progress',  # 3
    'Technical report',  # 4
    'Book',  # 5
    'Book chapter'  # 6
  ]



  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
  #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:yucheng@rsmas.miami.edu"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "https://twitter.com/fischcheng"

  [[params.social]]
    icon = "facebook"
    icon_pack = "fa"
    link = "https://www.facebook.com/fischcheng"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.com/citations?user=j65KEFYAAAAJ&hl=en"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "https://github.com/fischcheng"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 4

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 5

[[menu.main]]
  name = "Works"
  url = "#works"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 7



[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

[languages.en]
  languageCode = "en-us"